# Changes here will be overwritten by Copier
_commit: v0.4.1
_src_path: https://github.com/linkml/linkml-project-copier
add_example: true
copyright_year: '2025'
email: my-name@my-org.org
full_name: M
gh_action_docs_preview: true
gh_action_pypi: true
github_org: isrp
license: MIT
project_description: This is the project description.
project_name: isrp-linkml
project_slug: isrp_linkml

